import traceback

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.routers import demo_cases, screening

app = FastAPI(
    title="SentinX API",
    description=(
        "AI-based fake identity & document screening backend. "
        "Real MRZ checksum validation (ICAO 9303), real ELA tamper forensics, "
        "and OpenCV-based face similarity, fused into an explainable risk verdict."
    ),
    version="0.1.0",
)

# Wide-open CORS so the static prototype HTML (opened via file:// or any
# quick static server) can call this API during development / demo day.
# Tighten allow_origins to your actual frontend origin before any real
# deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(screening.router)
app.include_router(demo_cases.router)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """
    Return unhandled errors as JSON *with* CORS headers.

    Why this exists: FastAPI's CORSMiddleware does not attach
    Access-Control-Allow-Origin to a response generated by an unhandled
    exception. The browser then reports a misleading "blocked by CORS
    policy" error that hides the actual 500, which makes debugging from
    the frontend almost impossible. This handler makes the real error
    message visible in the browser instead.
    """
    traceback.print_exc()
    return JSONResponse(
        status_code=500,
        content={"detail": f"{type(exc).__name__}: {exc}"},
        headers={
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Credentials": "true",
        },
    )


@app.get("/", tags=["meta"])
def root():
    return {
        "name": "SentinX API",
        "status": "ok",
        "docs": "/docs",
        "endpoints": ["/api/screen", "/api/demo-cases"],
    }


@app.get("/health", tags=["meta"])
def health():
    return {"status": "ok"}
